### ISSUE TITLE
Make a Discord bot plugin

### ISSUE THREAD

**Issue by NorbiPeti** [TBMCPlugins/ButtonLaboratoryPlugin#4]
It could have features like:
- Adding the Minecraft role to players
- Forward mails/offline messages to Discord PMs
- Some kind of public messaging too
- Player/user flairs as roles (could be for other users too, not just Miencrafters)
- Post announcements to the server from Discord and vice-versa
- Post subreddit updates as well (also make Reddit interaction/bots separate too and use APIs)

**Comment by Ghostise** [comment]
Make the bot also announce new reddit posts on discord. They should be posted into #general.

**Comment by alisolarflare** [comment]
will be included in buttondevteam.alisolarflare.DiscordPlugin on my next commit

**Comment by alisolarflare** [comment]
aaaand bot created in C# seperate program, writing the code now

**Comment by alisolarflare** [comment]
_realized the shit I've gotten myself into_

**Comment by NorbiPeti** [comment]
https://github.com/TBMCPlugins/DiscordPlugin/commit/842f8a63b7a67d299aefacb6cf6cc0406d078b4c

It can connect!

**Comment by NorbiPeti** [comment]
@Ghostise https://github.com/TBMCPlugins/DiscordPlugin/issues/2 Posting announcements work.
